logging:
  level:
    net.shyshkin: debug
spring:
  application:
    name: spring-rsocket
  rsocket:
    server:
      port: 6565
app:
  register-clients: true
  notification:
    route: batch.job.response