version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  stock-service:
    image: artarkatesoft/stock-service

  user-service:
    image: artarkatesoft/user-service
    environment:
      "spring.data.mongodb.host": mongo
    depends_on:
      - mongo

  trading-service:
    image: artarkatesoft/trading-service
    environment:
      "spring.data.mongodb.host": mongo
      "app.clients.user-service.host": user-service
      "app.clients.stock-service.host": stock-service
    ports:
    - 8080:8080
    depends_on:
      - mongo
      - user-service
      - stock-service

volumes:
  mongo-data: