### fire-and-forget
FNF math.service.print
Host: tcp://127.0.0.1:6565
Content-Type: application/json

3

### request-response
RSOCKET math.service.find_square
Host: 127.0.0.1:6565
Content-Type: application/json

14

#### request-stream - DOES NOT WORK
#STREAM math.service.table
#Host: 127.0.0.1:6565
#Content-Type: application/json
#
#2
