spring:
  application:
    name: trading-service
  data:
    mongodb:
      authentication-database: admin
      database: tradeservice
      host: localhost
      port: 27017
      username: username
      password: password
logging:
  level:
    net.shyshkin: debug

app:
  clients:
    user-service:
      host: localhost
      port: 6563
    stock-service:
      host: localhost
      port: 6565



